<main class="pt-8 pb-16 lg:pt-16 lg:pb-24">
    <div class="flex justify-between px-4 mx-auto max-w-screen-xl ">
        <article class="mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert">
            <header class="mb-4 lg:mb-6 not-format">
                <h1 class="text-black mb-4 text-3xl font-extrabold leading-tight lg:mb-6 lg:text-4xl">Acceptable Use Policy</h1>
            </header>
            
            <div class="mt-10">
                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">1. Introduction</h3>
                <p>The Acceptable Use Policy (“AUP”) applies to your use of the website getadoctorsnote.org (hereafter referred to as "the site") which generates fake doctor's notes intended solely for entertainment or joke purposes.</p>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">2. Acceptance of Terms</h3>
                <p>By accessing the site, you agree to be bound by the terms of this AUP and our Terms of Service (“ToS”), and comply at all times with this policy and any other policies or guidelines.</p>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">3. Purpose</h3>
                <p>The site is designed to generate fake doctor's notes for amusement purposes only. These notes should not, under any circumstances, be used in a fraudulent manner, professionally, or for any purposes other than entertainment or a joke.</p>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">4. Prohibited Use</h3>
                <p>The prohibited uses include, but are not limited to, the following:</p>
                <ul>
                <li>a. Misuse: You must not use the site to create false doctor's notes for fraudulent purposes or any action that may result in harmful consequences.</li>
                <li>b. Academic or Professional Misconduct: The notes generated from the site must not be used to misrepresent an illness or personal situation in a professional or academic realm.</li>
                <li>c. Legal misconduct: The use of fake doctor's notes generated by our website in a manner that could contravene any local, state, national, or international laws is strictly prohibited.</li>
                </ul>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">5. Sanctions for Misuse</h3>
                <p>If we find any abuse or misuse of our resources, we reserve the right to suspend or terminate access to the site without prior notice at our discretion. We also retain the right to take legal action against anyone who uses our service in a manner that contravenes this Acceptable Use Policy.</p>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">6. Policy Updates</h3>
                <p>We reserve the right to revise, supplement, or replace the AUP at any time. It is your responsibility to review the AUP regularly to keep yourself updated. Your continued use of the site after the changes constitutes your acceptance of the new AUP.</p>

                <h3 class="mt-4 text-black mb-4 text-2xl font-extrabold leading-tight lg:mb-6 lg:text-3xl">7. Contact</h3>
                <p>If you become aware of misuse of the services provided by this site in violation of this AUP, please contact us at topperbrown2k@gmail.com.</p>

                <p>By using this site, you acknowledge that you have read, understood and agreed to comply with the terms of our AUP setting out expectations for responsible and legitimate usage of our website and its features.</p>

            </div>
            
        <footer>
            <h4 class="mt-10 text-black mb-4 text-xl font-semibold leading-tight lg:mb-6 lg:text-2xl">Please find our Disclaimer and Acceptable Use Policy below</h4>

            <div class="flex gap-3">
                <a href="/disclaimer" class="text-blue-600 text-lg underline">Disclaimer</a>
                <a href="/terms" class="text-blue-600 text-lg underline">Terms of Service</a>
            </div>
        </footer>
        
        </article>    
    </div>       
</main>